### ISSUE TITLE
Decompilation-line to binary-address mapping

### ISSUE THREAD

**Issue by mahaloz** [revng/revng-c#4]
Hello, and congratulations on the open-sourcing :). 

I wanted to know if there is any way to collect the addresses associated with each line of decompilation. As an example, some decompilation like:
```c
int main() {
    int x = 0;
    puts("hello");
    puts(x);
    return x;
}
```

It might have mapping like so:
```python
lines_to_addr = {
    0: [0x400000, 0x400008],
    1: [0x400010, 0x400020, ...]
    ...
}
```

I ask for the potential to evaluate the new version of revng.
In the [SAILR](https://github.com/mahaloz/sailr-eval) paper, we evaluated most decompilers using our speed-improved version of graph edit distance. 
To gain that speed improvement, we had to utilize source-to-binary-to-dec mappings that allowed us to chunk the computation space. If this mapping is exposed, it becomes much more feasible to attempt a full eval on revng. 

Thank you!

**Comment by aleclearmind** [comment]
Hi and thanks!

There is a mapping! The mapping is best effort, in the sense that some references back to the original binary get lost due to optimizations, but we have [a task on our roadmap](https://rev.ng/roadmap#feature-842) to improve the situation.

If you're interested, I can better detail how we track what was generated from where, but, in short, we exploit LLVM's debug metadata, but instead of referencing `file.c:line:column` we reference addresses into the original program (see [`AttachDebugInfo`](https://github.com/revng/revng/blob/develop/lib/EarlyFunctionAnalysis/AttachDebugInfo.cpp)).

Nevertheless, it should be rather easy to get what you're looking for: the decompiled code we emit is wrapped in [PTML](https://docs.rev.ng/references/ptml/). Just take a look at the [Navigation attributes](https://docs.rev.ng/references/ptml/#navigation-attributes) section, it should be self-explanatory.

We use this information to let the user navigate from decompiled code to assembly and vice-versa.

If you have other issues, please consider registering to discuss.rev.ng, we'd like to keep GitHub issues for issues with rev.ng and use discuss.rev.ng for general discussion.

**Comment by mahaloz** [comment]
Thanks @aleclearmind, that clears it up more. I've messed around with it and it should be good enough to parse out.
